function out1 = bodyFrame(in1)
%bodyFrame
%    OUT1 = bodyFrame(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Sep-2024 20:30:47

zeta_stand = in1(5,:);
t2 = cos(zeta_stand);
t3 = sin(zeta_stand);
out1 = reshape([t2,t3,0.0,-t3,t2,0.0,0.0,0.0,1.0],[3,3]);
end
