function r_eng_COM = engineCOM(in1,in2)
%engineCOM
%    r_eng_COM = engineCOM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Sep-2024 20:30:47

beta = in1(1,:);
gamma = in1(2,:);
l_eng = in2(7,:);
zeta_stand = in2(5,:);
t2 = cos(beta);
t3 = cos(gamma);
t4 = sin(gamma);
t5 = cos(zeta_stand);
t6 = sin(zeta_stand);
r_eng_COM = [(l_eng.*(t4.*t6-t2.*t3.*t5))./2.0;l_eng.*(t3.*t6+t2.*t4.*t5).*(-1.0./2.0);(l_eng.*t5.*sin(beta))./2.0];
end
