function out1 = engineAttachments(in1,in2)
%engineAttachments
%    OUT1 = engineAttachments(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Sep-2024 20:30:47

beta = in1(1,:);
gamma = in1(2,:);
l_attach = in2(3,:);
r_attach = in2(4,:);
zeta_stand = in2(5,:);
t2 = cos(beta);
t3 = cos(gamma);
t4 = sin(beta);
t5 = sin(gamma);
t6 = cos(zeta_stand);
t7 = sin(zeta_stand);
t8 = t3.*t7;
t9 = t5.*t7;
t10 = l_attach.*t4.*t6;
t11 = t2.*t3.*t6;
t12 = t2.*t5.*t6;
t13 = -t11;
t14 = t8+t12;
t15 = l_attach.*t14;
t16 = t9+t13;
t17 = l_attach.*t16;
t18 = -t15;
out1 = reshape([t17+r_attach.*t3.*t4,t18+r_attach.*t4.*t5,t10+r_attach.*t2,t17-r_attach.*(t2.*t8+t5.*t6),t18+r_attach.*(t3.*t6-t2.*t9),t10+r_attach.*t4.*t7],[3,2]);
end
