function out1 = engineFrame(in1,in2)
%engineFrame
%    OUT1 = engineFrame(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Sep-2024 20:30:47

beta = in1(1,:);
gamma = in1(2,:);
zeta_stand = in2(5,:);
t2 = cos(beta);
t3 = cos(gamma);
t4 = sin(beta);
t5 = sin(gamma);
t6 = cos(zeta_stand);
t7 = sin(zeta_stand);
out1 = reshape([-t5.*t7+t2.*t3.*t6,t3.*t7+t2.*t5.*t6,-t4.*t6,-t5.*t6-t2.*t3.*t7,t3.*t6-t2.*t5.*t7,t4.*t7,t3.*t4,t4.*t5,t2],[3,3]);
end
