function r_moment_arm = momentArm(in1,in2)
%momentArm
%    R_MOMENT_ARM = momentArm(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Sep-2024 20:30:47

beta = in1(1,:);
gamma = in1(2,:);
l_attach = in2(3,:);
zeta_stand = in2(5,:);
t2 = cos(beta);
t3 = cos(gamma);
t4 = sin(gamma);
t5 = cos(zeta_stand);
t6 = sin(zeta_stand);
r_moment_arm = [l_attach.*(t4.*t6-t2.*t3.*t5);-l_attach.*(t3.*t6+t2.*t4.*t5);l_attach.*t5.*sin(beta)];
end
