function out1 = standAttachments(in1)
%standAttachments
%    OUT1 = standAttachments(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Sep-2024 20:30:47

x_dist = in1(1,:);
y_dist = in1(2,:);
zeta_stand = in1(5,:);
t2 = cos(zeta_stand);
t3 = sin(zeta_stand);
t4 = t2.*y_dist;
t5 = t3.*y_dist;
out1 = reshape([t4,t5,x_dist,t4-t3.*x_dist,t5+t2.*x_dist,0.0],[3,2]);
end
